### ISSUE TITLE
Validate only one instance of Dat Desktop is running

### ISSUE THREAD

**Issue by yoshuawuyts** [datproject/dat-desktop#150]
As per https://github.com/datproject/dat-desktop/issues/147 we probably want to validate only one instance of dat-desktop is running.

### Todos
- [x] investigate how to prevent booting if an instance of Desktop is already running
- [x] write implementation to provide this check; show a nice, user-friendly message if it's the case
- [x]  split off implementation to a separate module

**Comment by juliangruber** [comment]
> investigate how to prevent booting if an instance of Desktop is already running

we can just catch the lock error on the leveldb instance for this :)

**Comment by yoshuawuyts** [comment]
There's also https://github.com/republicwireless-open/electron-single-instance which in turn recommends using [app.makeSingleInstance()](https://github.com/atom/electron/blob/master/docs/api/app.md#appmakesingleinstancecallback) - maybs that's a good one to use?
