### ISSUE TITLE
crash reporting

### ISSUE THREAD

**Issue by juliangruber** [datproject/dat-desktop#21]
using crashpad

- priority is catching application bugs, not electron hard crashes. so if hypercore for example throws an exception we should grab the stacktrace and send it to our crash reporting endpoint
- if we can do electron app crash reporting thats a bonus 

---
### todos
- [x] create crash reporting service ([repo](https://github.com/yoshuawuyts/crash-reporter-service))
- [x] deploy crash reporting service
- [ ] make dat-desktop phone home when it crashes

(edited by @yoshuawuyts)

**Comment by yoshuawuyts** [comment]
Started work on a crash report server here https://github.com/yoshuawuyts/crash-reporter-service

**Comment by yoshuawuyts** [comment]
server now accessible on https://crash-reporter.dat.land
