### ISSUE TITLE
logging, crash reporting & uncaught exceptions

### ISSUE THREAD

**Issue by yoshuawuyts** [datproject/dat-desktop#244]
Currently we send a crash report whenever there's an uncaught exception. This requires a user to be online at the time though. I thought we could use `electron.crashReporter` for this, but [apparently they don't consider exceptions to be crashes](https://github.com/electron/electron/issues/6496). So we'll need to do some tinkering on our end to make sure this is handled correctly.

---
### Todo
- [ ] write an `uncaughtException` / `unhandledRejection` handler with the same API as [electron.crashReporter](https://github.com/electron/electron/blob/master/docs/api/crash-reporter.md)
- [ ] use the `crashReporter` in both the `renderer` and `server` process
- [ ] update the `electron-crash-reporter-service` to handle electron crash reports (https://github.com/yoshuawuyts/electron-crash-report-service/issues/5)

### Further questions
- how do we report userland errors? e.g. incorrect input and the like; thing not being able to be created? I feel this might be useful feedback to improve on, but should we? What are the tradeoffs? (e.g. privacy)

---
cc/ @juliangruber What do you think?
cc/ @maxogden What's your take on analytics / error reporting for our Dat products?

**Comment by yoshuawuyts** [comment]
Actually this is kinda important - scheduling for the next milestone

**Comment by yoshuawuyts** [comment]
Alright, I'm picking this one up

**Comment by karissa** [comment]
Nice, noticed that too. I would think crash reporting would include exception handling by default, I'm sure other projects will be able to use this contribution too!

**Comment by yoshuawuyts** [comment]
Talked to feross today; linked me to all his things :tada:

### links
- [telemetry client](https://github.com/feross/webtorrent-desktop/blob/master/src/renderer/lib/telemetry.js)
- [crash reporter client](https://github.com/feross/webtorrent-desktop/blob/master/src/crash-reporter.js)
- [telemetry server](https://github.com/feross/webtorrent.io/blob/master/server/desktop-api.js#L68)
- [crash reporter server](https://github.com/feross/webtorrent.io/blob/master/server/desktop-api.js#L175)

### raw
```txt
23:37 <feross> our client-side telemetry is here: https://github.com/feross/webtorrent-desktop/blob/master/src/renderer/lib/telemetry.js
23:37 <feross> and crash reporting is here: https://github.com/feross/webtorrent-desktop/blob/master/src/crash-reporter.js
23:37 <feross> server side is here: https://github.com/feross/webtorrent.io/blob/master/server/desktop-api.js#L68
23:38 <feross> server side for crash reports is here: https://github.com/feross/webtorrent.io/blob/master/server/desktop-api.js#L175
```
