### ISSUE TITLE
Week 12 release checklist

### ISSUE THREAD

**Issue by yoshuawuyts** [datproject/dat-desktop#305]
- [x] create preview release
- [x] test resulting binary
- [x] write patch notes
- [x] publish final binary
- [x] tweet about release

cc/ @juliangruber think we can cut a new release today or tomorrow?

**Comment by juliangruber** [comment]
I'm aiming for today

**Comment by yoshuawuyts** [comment]
released & done
